### ISSUE TITLE
Does not compile under Windows

### ISSUE THREAD

**Issue by mguillemot** [synrc/fs#13]
https://github.com/synrc/fs/commit/1d12c6122e019c513a92758483d8a89c5086c8e9 commented out the compilation of inotifywait.exe on Windows in rebar.conf, because a pre-build binary is now included in the source tree.

But https://github.com/synrc/fs/commit/e3e8f03fc064585dd4410690c05c2dd31d4a89c8 re-introduced the pre_hook. This prevents fs to be used as a dependency to other projects, especially phoenix_live_reload (and thus phoenix itself):

Example output from `mix deps.compile` on a brand-new Phoenix 0.11 project on a fresh install of Elixir 1.0.4 on Windows 7 64bit:

```
==> fs (compile)
'make' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Command [compile] failed!
** (Mix) Could not compile dependency fs, escript.exe "c:/Users/Erhune/.mix/rebar" command failed. If you want to recompile this dependency, please run: mix deps.compile fs
```

I think https://github.com/synrc/fs/commit/e3e8f03fc064585dd4410690c05c2dd31d4a89c8 should be reverted and the instructions to build inotifywait.exe on Windows be put in a documentation file for those who really need it.

**Comment by electricFeel** [comment]
+1
