### ISSUE TITLE
Upload newest package to hex.pm

### ISSUE THREAD

**Issue by gleber** [synrc/fs#20]
Currently hex.pm contains only version 0.9 as seen here https://hex.pm/packages/fs

Please upload the latest version, so it can be seamlessly used with `rebar3`

**Comment by 5HT** [comment]
OK, just remind me the bash sequence how to `publish` :-)
I know there is two ways of publish, one is correct and another is legacy.

**Comment by gleber** [comment]
Make sure you have rebar3 installed (for example):

```
cd /usr/local/bin/
sudo wget https://s3.amazonaws.com/rebar3/rebar3
chmod a+rx rebar3
```

Make sure your `~/.config/rebar3/rebar.config` contains

```
{plugins, [rebar3_hex]}.
```

Later do 

```
rebar3 hex user auth  # to "log in" your hex.pm account
rebar3 hex publish
```

**Comment by 5HT** [comment]
```
Proceed? ("Y")> Y
===> Status Code: HTTP status code: 400
Hex Error: Bad request
```

**Comment by egobrain** [comment]
> ===> Status Code: HTTP status code: 400
> Hex Error: Bad request

Check the app version. Some times it looks like:

> Publishing myapp 1.0.0+build.6.reff0aec24

Hex.pm supports semver without appending.

**Comment by lpil** [comment]
Close this? :)
