### ISSUE TITLE
Is it possible to silence the warnings from inotifywait on Linux?

### ISSUE THREAD

**Issue by lpil** [synrc/fs#22]
When I start my application I get a garbled message like so:

```
Interactive Elixir (1.2.3) - press Ctrl+C to exit (type h() ENTER for help)
Setting up watches.  Beware: since -r was given, this may take a while!
                                                                       Watches established.
       iex(1)>
```

Is it possible to silence this?

**Comment by yolk** [comment]
Should work if we add `--quiet` to the `inotifywait` call in `inotifywait.erl`

**Comment by lpil** [comment]
Is there a way to do this without forking `fs` to modify the code?

**Comment by yolk** [comment]
I guess you could add a shell script named inotifywait in your path above /usr/bin/inotifywait that stubs inotifywait and always calls /usr/bin/inotifywait with the quiet-flag. But I think a pull request would be easier and more stable ;)
