### ISSUE TITLE
directory that application is started in is always watched regardless of the path passed into start_link

### ISSUE THREAD

**Issue by retrogradeorbit** [synrc/fs#29]
When I fs:start_link(fs_watcher, "/path/to/my/dir"), the inotify command is set up to watch that path "/path/to/my/dir", but also the current working directory the application was started in is also watched. This leads to the application crashing if the user starts it in a directory too close to root, with too many child directories, as it causes too many paths to be watched and that exceeds the value set in /proc/sys/fs/inotify/max_user_watches.

A classic example of this is if the application is setup as a system process under something like upstart. Here, the cwd is usually the root path "/", and then the application crashes with:

```
Failed to watch /; upper limit on inotify watches reached!
Please increase the amount of inotify watches allowed per user via `/proc/sys/fs/inotify/max_user_watches'.
```

**Comment by proger** [comment]
This was introduced in #18, ping @5HT @liveforeverx

**Comment by proger** [comment]
It looks like you can try mitigating this by setting `backwards_compatible` to `false`: https://github.com/synrc/fs/blob/master/src/fs_app.erl

@5HT any reason to keep backwards compatibility?

**Comment by 5HT** [comment]
for me no, maybe we should ask Elixir developers

**Comment by liveforeverx** [comment]
@retrogradeorbit : Set `backwards_compatible` to `false` to disable this behaviour (as @proger suggests).
