### ISSUE TITLE
0.2.12 fails to compile on macOS

### ISSUE THREAD

**Issue by green-arrow** [synrc/fs#40]
I recently started up a new Phoenix project, and get an immediate failure when compiling dependencies due to `:fs`:

```
===> error: {badmatch,{error,no_scheme}} [{rebar3_hex_http,maybe_setup_proxy,
                                           2,
                                           [{file,
                                             "/Users/andrewwa/Developer/gitlab/shadow_lane_server/deps/fs/_build/default/plugins/rebar3_hex/src/rebar3_hex_http.erl"},
                                            {line,122}]},
                                          {rebar3_hex,init,1,
                                           [{file,
                                             "/Users/andrewwa/Developer/gitlab/shadow_lane_server/deps/fs/_build/default/plugins/rebar3_hex/src/rebar3_hex.erl"},
                                            {line,7}]},
                                          {rebar_state,
                                           '-create_logic_providers/2-fun-0-',
                                           2,
                                           [{file,
                                             "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_state.erl"},
                                            {line,409}]},
                                          {lists,foldl,3,
                                           [{file,"lists.erl"},{line,1263}]},
                                          {rebar_state,
                                           create_logic_providers,2,
                                           [{file,
                                             "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_state.erl"},
                                            {line,408}]},
                                          {rebar_plugins,
                                           '-handle_plugins/4-fun-0-',4,
                                           [{file,
                                             "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                                            {line,84}]},
                                          {lists,foldl,3,
                                           [{file,"lists.erl"},{line,1263}]},
                                          {rebar_plugins,handle_plugins,4,
                                           [{file,
                                             "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                                            {line,82}]}]
```

I've tried removing `build`, `_deps`, and reinstalling `rebar`, none of which have worked.

Elixir: 1.3.4
Erlang: 19.2
macOS: 10.12.3

**Comment by alex88** [comment]
Same here but with a different error

https://gist.githubusercontent.com/alex88/d43db0078801f0af906ed0da60b823e7/raw/789d1fbd8b00f13d247889bf91e702f5aecce8f3/gistfile1.txt

**Comment by jmcaffee** [comment]
I'm seeing the same as @alex88, running Ubuntu 16.04. I've opened an issue under [elixir-koans](https://github.com/elixirkoans/elixir-koans/issues/172) but it probably belongs here.

**Comment by 5HT** [comment]
Please check. I removed `pc` plugin.

**Comment by alex88** [comment]
@5HT thanks it works fine now, you can release a new one 😄

**Comment by jmcaffee** [comment]
@5HT, I concur. Fixed my issue!

Thanks

**Comment by felipesere** [comment]
@5HT Are you planning to do a fresh release soon? The Elixir Koans project depends on exfswatch which depends on this we have an outstanding issue to fix code reload 😄

**Comment by 5HT** [comment]
I don't believe you. The professional level of elixir developers are so poor that you need to provide evidence before I trust you.

**Comment by felipesere** [comment]
Sorry if I was a bit blunt 😄 

This is the issue against the Elixir Koans: https://github.com/elixirkoans/elixir-koans/issues/172
which points to https://github.com/falood/exfswatch/issues/17
which is waiting for a fresh release with the fix?

Let me know if I got it wrong 😞

**Comment by 5HT** [comment]
I don't care. I need stacktrace or proof that my project is not working.
1. First you shpuld provide evidence it is not working in Erlang.
2. Then you should provide evidence it is not working with Phoenix live reload.
3. Then you can try to inject here your bullshit projects.

If you don't like the quality of the project you can fork and fix it. Or rewrite to Elixir.

**Comment by 5HT** [comment]
Did you even  try to see changeset from master to  0.12
https://github.com/synrc/fs/compare/2.12.0...master
?
How it can helps you?

**Comment by felipesere** [comment]
I appreciate that the burden of proof is on my end. You have already fixed this in https://github.com/synrc/fs/commit/755ed15588ad9ea11a86b314e1b09e7a87060f3c
All I am wondering if the there is a need to release the current code as 2.12.1 onto hex.pm?

This isn't a critique of the project, the code quality or any of that.

**Comment by 5HT** [comment]
This code was added by @liveforeverx 
Why he did that?
So rebar3 is not compatible with elixir? Ok, then.
Fucking tools: Elixir, Rebar3. I really think I should break compatibility with all that bullshit.
And stay compatible only with our mad.

**Comment by 5HT** [comment]
Jose was asked me to put EXE file in repository! This is nonsense!
Really Elixir approach to development is a problem.

**Comment by felipesere** [comment]
@5HT I think this out of my league. Sorry I caused any grievances. I'll drop off now and try to come up with an alternative solution. Thank you for your time.

**Comment by 5HT** [comment]
Try it now: https://hex.pm/packages/fs/3.4.0

**Comment by liveforeverx** [comment]
@5HT I have added it, that package can be compiled with rebar3 and pushed to hex with rebar3 without needing to have elixir installed....

Probably, if only rebar_hex plug-in will be removed, it will work.
Somehow rebar3 is fragile in this aspect...
