### ISSUE TITLE
latest fs does not work on Mac 10.12.5

### ISSUE THREAD

**Issue by dongyuwei** [synrc/fs#49]
fs:start_link(fs_watcher, "/tmp/").
** exception exit: undef
     in function  mad_repl:load_file/1
        called as mad_repl:load_file("deps/fs/priv/mac_listener")
     in call from fs:mad_file/1 (/Users/yuwdong/code/erlang/CommonJS.erl/_build/default/lib/fs/src/fs.erl, line 43)
     in call from fs_sup:has_executable/1 (/Users/yuwdong/code/erlang/CommonJS.erl/_build/default/lib/fs/src/fs_sup.erl, line 27)
     in call from fs_sup:init/1 (/Users/yuwdong/code/erlang/CommonJS.erl/_build/default/lib/fs/src/fs_sup.erl, line 17)
     in call from supervisor:init/1 (supervisor.erl, line 294)
     in call from gen_server:init_it/6 (gen_server.erl, line 328)
     in call from proc_lib:init_p_do_apply/3 (proc_lib.erl, line 247)

## test envs:
1. Mac 10.12.5
2. Erlang/OTP 19 [erts-8.3] [source-d5c06c6] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]
3. rebar3 -v
    rebar 3.3.6+build.3769.ref4bac0ed2 on Erlang/OTP 19 Erts 8.3

**Comment by 5HT** [comment]
ensure you have working `code:priv_dir(fs)` otherwise your app is not OTP compatible

**Comment by dongyuwei** [comment]
but just 6 month ago, it did work as expected. see https://github.com/dongyuwei/CommonJS.erl/blob/master/rebar.lock and the commit log.

By saying "ensure you have working code:priv_dir(fs)", what's the exact meaning? Sorry I can't understand it. My project is generated by `rebar3 new lib commonjs`
